name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
      - development
  pull_request:
    types: [closed]
    branches:
      - master
      - development

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Create Static Web App Config
        run: |
          echo '{
            "navigationFallback": {
              "rewrite": "/index.html",
              "exclude": ["/images/*", "/static/*", "/*.{png,jpg,gif,svg,ico,json,css,js}"]
            },
            "routes": [
              {
                "route": "/*",
                "serve": "/index.html",
                "statusCode": 200
              }
            ],
            "responseOverrides": {
              "404": {
                "rewrite": "/index.html",
                "statusCode": 200
              }
            }
          }' > staticwebapp.config.json
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_POND_05240570F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "build"
          skip_app_build: false
          app_artifact_location: "build"
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_TENANT_ID: ${{ secrets.REACT_APP_TENANT_ID }}
          REACT_APP_SUPPORT_EMAIL: ${{ secrets.REACT_APP_SUPPORT_EMAIL }}
          CI: false
          
          