name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Add debug logging
      - name: Debug Info
        run: |
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Directory contents:"
          ls -la
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_POND_05240570F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "build"
          skip_app_build: false
          app_artifact_location: "build"
          deployment_environment: "production" # Add this line
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_TENANT_ID: ${{ secrets.REACT_APP_TENANT_ID }}
          CI: false
          NODE_OPTIONS: "--max-old-space-size=4096" # Add memory allocation

      # Add error handling
      - name: Handle Deployment Error
        if: failure()
        run: |
          echo "Deployment failed. Checking build directory:"
          ls -la build/
          echo "Checking configuration files:"
          cat staticwebapp.config.json